### ISSUE TITLE
Vignette Creation

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refnet2#18]
Emilio is working on giving Matt/I edits.

**Comment by aurielfournier** [comment]
We need to either build a function, or supply code in the vignette to describe how to get summary information about the authors/papers. Such as average number of authors per paper

We need to include, in the vignette, a summary of possible outputs
1 - dataframe for social network analysis
2 - plots
3 - dataframe to build plots on your own

we should also consider building a graphing specific vignette,

**Comment by aurielfournier** [comment]
Need to make sure its clear in the vignette that the read* function can do a single file or a whole directory

**Comment by aurielfournier** [comment]
Do we want to include instructions on how to download the WOS files themselves? a Step 0 if you will?

**Comment by aurielfournier** [comment]
@embruna do you want me to dig into the literature and write up this part of the intro to the vignette

> Define, the history of bibliometric data, typical analyses and what they tell us.

Or is that something you'd like to tackle?

**Comment by aurielfournier** [comment]
I've added in all the photos as a apart of the package

**Comment by embruna** [comment]
I'm working on the vignette in a bot and will add some text on the history+

**Comment by aurielfournier** [comment]
Ok I think I've gotten all your comments addressed and I did a close read for spelling. How do you feel about it now @embruna ?
