### ISSUE TITLE
text file stictcher function

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refnet2#27]
because WOS only allows one to download references in batches of 500, any analysis based on >500 records will require stitching together a bunch of text files downloaded from WOS.  I’d alredy done this for the files we’ve been working with, but it would probably be a good idea to include the process for doing this in refnet.  Fortunately, I’ve already written it - it’s a script called `WOS-download-sticther` in the main refnet2 folder.  It takes all the files in a subfolder of the `data` folder,  read-authors them, then binds the csv files generated for each one into a single file that can be analyzed.  We should include this in refnet, no?

The only thing is that one needs to do a few things differently to read them into refnet and then run read_authors on them, You can see an example in  `UsingRefnet.Rmd` look for `WOS2011_stitched`, `WOS2018_stitched`, and `FL2017_stitched`.  Should be an easy bit of work to convert this to a function

**Comment by aurielfournier** [comment]
@embruna 

read_references right now allows you to either read in one file, or a directory of files. Does that address this issue? 

If it doesn't, we should chat, because then I am confused.

**Comment by embruna** [comment]
ERMAHGERD. I had no idea that Forrest had built this in so I went and figured out how to do it myself.  YES, ignore what I said - though clearly we need to make this clear in the vignette and flow chart. smh
