### ISSUE TITLE
Address Parsing and Georeferencing as 2 steps

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#29]
The ```separate``` function was huge because it finally made it possible to do analyses based on institution.  Can we polish this and its output and add to the flow chart? eg., can we link individuals authors and the output in ```dat```?  Perhaps there are two things to do:

1) Allow users to run ```separate``` after ```refine_authors``` and add a column with the parsed institution name to ```authors``` in the ```foo_authors``` list 
 
2) Allow people to spit out csv file of ```dat``` with all the institutions, departments, etc for users who want this (with the caveat that it is messy output in some fields)

**Comment by embruna** [comment]
Yes, that's the code I meant. I was thinking about it in the step-by-step way for people less familiar with R. 

I know what I would want - a data frame of each unique author with their ID number, and the information we can parse out of the address (institution, country...maybe city or zip?). But people move, so some people will have multiple entries for institutions,country,city,zip). 

One way to make it easier might be to do it as part of ```refine_authors```, which already lists each author of each article - all we'd be doing is adding columns for their country, institution,etc **for that reference record*** to the end of that.

**Comment by embruna** [comment]
Would rOpenSci's [geoparser](https://github.com/ropensci/geoparser) be useful?

**Comment by aurielfournier** [comment]
Address parsing is now apart of `read_authors`.

it pulls out the university, department, postal code, country name, and address. 

I'll work next on getting the `address_lat_long()` function. so it just does the georeferencing

**Comment by embruna** [comment]
Cool. Does it append it to an existing output or does it spit out a separate one? Just want to update the vignette before I forget.

**Comment by embruna** [comment]
Found it, this is awesome.
