### ISSUE TITLE
PY and PT data missing after read_authors

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#30]
The data that should be in the PT and PY columns (publication type and publication year, respectively) is missing after running the WOS files through ```read_authors```.   Interestingly, the columns in the csv files are blank, not filled with NAs. 

(a few other columns have this too, but these are the two really critical ones - especially PY!)

**Comment by aurielfournier** [comment]
Oh good catch.

**Comment by aurielfournier** [comment]
and fixed!

eb_authors$master$PT & eb_authors$master$PY now work!
