### ISSUE TITLE
duplicate records by Read_references 

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#31]
The same reference can appear in different searches (e.g., I'm guessing a search for TW = "rails" and another AU = "Fournier" will almost certainly have a few papers in common).  I discovered that if saved in the same directory and imported with ```read_references```, all records in both files - including duplicates - are processed and retained. 

I tested for this using by reading in 2 copies of same file (only file name differed); they are saved in the ```data``` folder in the sub-folder ```dupe_test```. 

Read in and process the files:

`dupe_references <- read_references("./data/dupe_test", dir=TRUE, filename_root="./output/dupe_test")
`

I then eliminated duplicates based on the Accession Number Field (UT):  

`dupe_references<-distinct(dupe_references, UT, .keep_all = TRUE)`

Should this go inside the ```read-references``` function?

**Comment by aurielfournier** [comment]
great catch, and yes, it makes sense to add it to `read_references` which I just did, and it works great!
