### ISSUE TITLE
Orcid ID (OI) & Researcher ID (RI) not being read in

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#33]
Neither the Orcid ID nor Reseearcher ID columns are being populated. I think the problem is in ```read_references``` and then cascading into ```read_authors```.  

Note: I had this problem but solved it before handing it over. Could it be the fields are being read in differently now, causing it to break?

**Comment by aurielfournier** [comment]
I just checked this, and they are being read through in my code. 

I checked it on the Ecology and EBpubs datasets.

**Comment by embruna** [comment]
Not sure what the problem was, because they are now being read in for me as well - no idea what the heck was going on. 2x with a few others, but if it works now I'll close it out.

**Comment by embruna** [comment]
I figured it out. I was using a bunch of WOS files downloaded in 2011, which was before they started including OI records. So I feel stupid and am closing this in 3...2...1....
