### ISSUE TITLE
read_authors error

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#37]
When I used read `read_authors`on the files in the data/LARR folder I got the following error message:

`1: Expected 3 pieces. Missing pieces filled with `NA` in 3718 rows [300, 417, 476, 491, 547, 600, 606, 612, 617, 618, 619, 620, 621, 622, 629, 630, 631, 632, 634, 635, ...]. ` 

I think this is because some of the authors have no affiliation, so the code for address parsing - whihc is now in `read_authors` - fails. Maybe a step to ID any author with NA in the address and insert "No Affiliation" when address parsing?

**Comment by aurielfournier** [comment]
done and done.
