### ISSUE TITLE
read_references: Publication year still not in csv but I know why

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#38]
When you run `read_references` the Publication Year is still blank in the csv file. I went back and it is in the dataframe, but if you do `foo_references$PY` you will see they are in the dataframe as `"1998\n"`.  As a result, they PY column in the csv file in the "output" folder is blank.

An easy fix, whihc I just did manually with the file I was working on. The function needs to have something like

```
foo_references$PY<-gsub("\n", "", foo_references$PY)  
foo_references$PY<-as.numeric(foo_references$PY)
```
line 1 deletes the \n, then line 2 converts the string to a numeric value and BOOM. saved in the csv.

**Comment by aurielfournier** [comment]
fixed! I made the change in `read_references`
