### ISSUE TITLE
read_references is leaving \n in cells  

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#39]
Many of the cells in the dataframe spit out by `read_references` (foo_references) have a \n tag in them (new line). This cases all kinds of formatting weirdness in .csv file (leading to confusion like in #33). It may also be part of the reason white spaces are being introduced (#28). In some cases the \n is there because the item associated with the field code is was too long for the WOS cell (e.g., the titles of papers are cut into multiple lines). In other cases it does actually indicate items in one cell, each on a different line (e.g., C1 lists the addresses for each author of a paper, with each address on a new line). 

I suggest eliminating \n in all columns. except those where different lines are different data. The only one I can think of off hand is C1. In that case it might make sense to separate each one by a ; or numbered brackets. eg. reference ID 4320 in WOS2018 has C1:

> Univ Fed Amazonas, Dept Biol, BR-69077000 Manaus, Amazonas, Brazil\nFed Univ Para, Dept Biol, CCB, BR-66075110 Belem, Para, Brazil.\nAssoc Kwata, F-97335 Cayenne, France.\nWildlife Conservat Soc, Gainesville, FL 32605 USA.\nWashington Univ, Sch Med, Dept Anat & Neurobiol, St Louis, MO 63110 USA.\n

resulting in

> Univ Fed Amazonas, Dept Biol, BR-69077000 Manaus, Amazonas, Brazil
> Fed Univ Para, Dept Biol, CCB, BR-66075110 Belem, Para, Brazil.
> Assoc Kwata, F-97335 Cayenne, France.
> Wildlife Conservat Soc, Gainesville, FL 32605 USA.
> Washington Univ, Sch Med, Dept Anat & Neurobiol, St Louis, MO 63110 USA.
>     

Maybe convert to: 

> [1] Univ Fed Amazonas, Dept Biol, BR-69077000 Manaus, Amazonas, Brazil [2] Fed Univ Para, Dept Biol, CCB, BR-66075110 Belem, Para, Brazil. [3] Assoc Kwata, F-97335 Cayenne, France. [4] Wildlife Conservat Soc, Gainesville, FL 32605 USA. [5] Washington Univ, Sch Med, Dept Anat & Neurobiol, St Louis, MO 63110 USA

**Comment by embruna** [comment]
PS This might be very useful for comparison: https://github.com/alberto-martin/read.wos.R/blob/master/report.Rmd

**Comment by birderboone** [comment]
Good catch. I hadnt thought of that yet. I'll get on white space deletion.

I personally like the numbered brackets, just adding a line break is literally just translating the '/n/ into R character format.

**Comment by birderboone** [comment]
And ofcourse, semicolons are used to seperate authors with the same address, so nix that idea. I used forward slash instead "/"
