### ISSUE TITLE
\n code has suck back into dataframes

### ISSUE THREAD

**Issue by embruna** [embruna/refnet2#41]
In the latest version almost all the cells have the "\n" code in them. They are read into excel with additional spaces or line breaks, and if you do 'summary(WOS2018_references)' you will see that this also weirds out almost all columns of the data frame (e.g., "NULL:10.1016/j.ecolmodel.2010.08.037\n". Should be an easy fix.

**Comment by birderboone** [comment]
Fixed. These linebreaks partially get introduced naturally in the WOS file, and partially because we put them there to split multi argument line items later, but i changed the important ones to a '/' and otherwise deleted line breaks. Had to update read_authors to address this too
